---
version: "3"

services:
  grpc_server:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      - GRPC_SERVER_PORT=50051
    ports:
      - "50051:50051"
  grpc_client:
    build:
      context: client
      dockerfile: Dockerfile
    environment:
      - GRPC_SERVER_HOST=grpc_server
      - GRPC_SERVER_PORT=50051
    depends_on:
      - grpc_server
    ports:
      - "8000:8000"
