# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import electricity_consumption_pb2 as electricity__consumption__pb2


class ElectricityConsumptionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetElectricityConsumption = channel.unary_stream(
                '/ElectricityConsumption/GetElectricityConsumption',
                request_serializer=electricity__consumption__pb2.Request.SerializeToString,
                response_deserializer=electricity__consumption__pb2.ConsumptionPoint.FromString,
                )


class ElectricityConsumptionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetElectricityConsumption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ElectricityConsumptionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetElectricityConsumption': grpc.unary_stream_rpc_method_handler(
                    servicer.GetElectricityConsumption,
                    request_deserializer=electricity__consumption__pb2.Request.FromString,
                    response_serializer=electricity__consumption__pb2.ConsumptionPoint.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ElectricityConsumption', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ElectricityConsumption(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetElectricityConsumption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ElectricityConsumption/GetElectricityConsumption',
            electricity__consumption__pb2.Request.SerializeToString,
            electricity__consumption__pb2.ConsumptionPoint.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
