# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: electricity_consumption.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65lectricity_consumption.proto\"\x15\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\t\"5\n\x10\x43onsumptionPoint\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x13\n\x0bmeasurement\x18\x02 \x01(\x02\x32V\n\x16\x45lectricityConsumption\x12<\n\x19GetElectricityConsumption\x12\x08.Request\x1a\x11.ConsumptionPoint\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'electricity_consumption_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=33
  _REQUEST._serialized_end=54
  _CONSUMPTIONPOINT._serialized_start=56
  _CONSUMPTIONPOINT._serialized_end=109
  _ELECTRICITYCONSUMPTION._serialized_start=111
  _ELECTRICITYCONSUMPTION._serialized_end=197
# @@protoc_insertion_point(module_scope)
